param(
    [string]$BaseUrl = "http://127.0.0.1:8080",
    [string]$Username = "admin",
    [string]$Password = "admin123",
    [string]$SampleDir = "D:\AI Demo\菁选\samples\runtime-demo-package",
    [string]$ZipPath = "D:\AI Demo\菁选\outputs\runtime-demo-package.zip",
    [string]$Title = "Runtime Demo Work"
)

$ErrorActionPreference = "Stop"

function Write-Step($message) {
    Write-Host ""
    Write-Host "==> $message" -ForegroundColor Cyan
}

function Ensure-SampleZip {
    if (Test-Path $ZipPath) {
        return
    }

    if (-not (Test-Path $SampleDir)) {
        throw "Sample directory not found: $SampleDir"
    }

    $zipParent = Split-Path -Parent $ZipPath
    if (-not (Test-Path $zipParent)) {
        New-Item -ItemType Directory -Force -Path $zipParent | Out-Null
    }

    Compress-Archive -Path (Join-Path $SampleDir '*') -DestinationPath $ZipPath -Force
}

function Invoke-ApiJson {
    param(
        [string]$Method,
        [string]$Uri,
        [hashtable]$Headers = @{},
        [object]$Body = $null
    )

    if ($null -ne $Body) {
        return Invoke-RestMethod -Uri $Uri -Method $Method -Headers $Headers -ContentType "application/json" -Body ($Body | ConvertTo-Json -Depth 8)
    }

    return Invoke-RestMethod -Uri $Uri -Method $Method -Headers $Headers
}

Write-Step "Ensuring sample zip exists"
Ensure-SampleZip
Write-Host "Sample zip: $ZipPath"

Write-Step "Logging in"
$login = Invoke-ApiJson -Method Post -Uri "$BaseUrl/api/auth/login" -Body @{
    username = $Username
    password = $Password
}
$token = $login.data.token
if (-not $token) {
    throw "Login failed: token missing"
}
$headers = @{ Authorization = "Bearer $token" }
Write-Host "Login ok"

Write-Step "Creating work"
$create = Invoke-ApiJson -Method Post -Uri "$BaseUrl/api/work/create" -Headers $headers -Body @{
    title = $Title
    summary = "Runtime demo integration test"
    techStack = "Spring Boot,Vue"
    advisor = "Codex"
    runDesc = "Generated by test-runtime-demo.ps1"
}
$workId = $create.data
if (-not $workId) {
    throw "Work creation failed: workId missing"
}
Write-Host "Work ID: $workId"

Write-Step "Uploading sample zip"
$form = @{
    file = Get-Item $ZipPath
    workId = $workId
}
$upload = Invoke-RestMethod -Uri "$BaseUrl/api/file/upload" -Method Post -Headers $headers -Form $form
Write-Host "Upload result:" ($upload | ConvertTo-Json -Depth 6)

Write-Step "Preparing runtime"
$prepare = Invoke-ApiJson -Method Post -Uri "$BaseUrl/api/runtime/$workId/prepare" -Headers $headers
Write-Host ($prepare | ConvertTo-Json -Depth 8)
if (-not $prepare.data.valid) {
    throw "Prepare failed"
}

Write-Step "Starting runtime"
$start = Invoke-ApiJson -Method Post -Uri "$BaseUrl/api/runtime/$workId/start"
Write-Host ($start | ConvertTo-Json -Depth 8)

Write-Step "Polling runtime status"
$status = $null
for ($i = 0; $i -lt 15; $i++) {
    Start-Sleep -Seconds 2
    $status = Invoke-ApiJson -Method Get -Uri "$BaseUrl/api/runtime/$workId/status"
    Write-Host ("Attempt {0}: {1}" -f ($i + 1), ($status.data.status))
    if ($status.data.status -eq "running") {
        break
    }
}

if ($null -eq $status -or $status.data.status -ne "running") {
    throw "Runtime did not reach running state"
}

$backendPort = $status.data.backendPort
$frontendPort = $status.data.frontendPort

Write-Step "Pinging backend and frontend"
$backendResponse = Invoke-RestMethod -Uri ("http://127.0.0.1:{0}/" -f $backendPort) -Method Get
$frontendResponse = Invoke-WebRequest -Uri ("http://127.0.0.1:{0}" -f $frontendPort) -UseBasicParsing

Write-Host "Backend response:" ($backendResponse | ConvertTo-Json -Depth 6)
Write-Host "Frontend status code:" $frontendResponse.StatusCode

Write-Step "Stopping runtime"
$stop = Invoke-ApiJson -Method Post -Uri "$BaseUrl/api/runtime/$workId/stop"
Write-Host ($stop | ConvertTo-Json -Depth 8)

Write-Step "Done"
Write-Host "Runtime integration flow completed for workId $workId"
