-- ============================================================
-- 集成测试 Schema（H2 MySQL 兼容模式）
-- 注意：不含 MySQL 专有语法（USE、ON DUPLICATE KEY UPDATE 等）
-- ============================================================

-- 角色
CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT NOT NULL,
    role_name VARCHAR(50) NOT NULL,
    role_code VARCHAR(50) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 用户
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(50) NOT NULL,
    role_id INT NOT NULL,
    class_id BIGINT DEFAULT NULL,
    avatar VARCHAR(255) DEFAULT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    email VARCHAR(100) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    first_login TINYINT NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_username (username)
);

-- 菜单
CREATE TABLE IF NOT EXISTS sys_menu (
    id BIGINT NOT NULL,
    menu_name VARCHAR(50) NOT NULL,
    parent_id BIGINT DEFAULT 0,
    path VARCHAR(200) DEFAULT NULL,
    permission VARCHAR(200) DEFAULT NULL,
    type TINYINT NOT NULL DEFAULT 1,
    icon VARCHAR(100) DEFAULT NULL,
    sort INT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 角色-菜单
CREATE TABLE IF NOT EXISTS sys_role_menu (
    id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_role_menu (role_id, menu_id)
);

-- 字典
CREATE TABLE IF NOT EXISTS sys_dict (
    id BIGINT NOT NULL,
    dict_type VARCHAR(50) NOT NULL,
    dict_label VARCHAR(100) NOT NULL,
    dict_value VARCHAR(100) NOT NULL,
    sort INT NOT NULL DEFAULT 0,
    remark VARCHAR(255) DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 日志
CREATE TABLE IF NOT EXISTS sys_log (
    id BIGINT NOT NULL,
    user_id BIGINT DEFAULT NULL,
    username VARCHAR(50) DEFAULT NULL,
    action VARCHAR(100) NOT NULL,
    target VARCHAR(255) DEFAULT NULL,
    target_id BIGINT DEFAULT NULL,
    ip VARCHAR(50) DEFAULT NULL,
    request_method VARCHAR(10) DEFAULT NULL,
    request_path VARCHAR(255) DEFAULT NULL,
    params TEXT DEFAULT NULL,
    result TINYINT NOT NULL DEFAULT 1,
    error_msg VARCHAR(500) DEFAULT NULL,
    duration BIGINT DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- 公告
CREATE TABLE IF NOT EXISTS sys_notice (
    id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    publisher_id BIGINT NOT NULL,
    publish_time DATETIME DEFAULT NULL,
    top_flag TINYINT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 通知
CREATE TABLE IF NOT EXISTS sys_notification (
    id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT DEFAULT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    ref_id BIGINT DEFAULT NULL,
    is_read TINYINT NOT NULL DEFAULT 0,
    read_time DATETIME DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- ==================== 业务表 ====================

-- 作品
CREATE TABLE IF NOT EXISTS work (
    id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary TEXT DEFAULT NULL,
    tech_stack VARCHAR(500) DEFAULT NULL,
    advisor VARCHAR(100) DEFAULT NULL,
    cover_url VARCHAR(500) DEFAULT NULL,
    video_url VARCHAR(500) DEFAULT NULL,
    run_desc TEXT DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    submitter_id BIGINT NOT NULL,
    submit_time DATETIME DEFAULT NULL,
    batch_id BIGINT DEFAULT NULL,
    view_count INT NOT NULL DEFAULT 0,
    like_count INT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 成员
CREATE TABLE IF NOT EXISTS work_member (
    id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    student_id BIGINT DEFAULT NULL,
    student_name VARCHAR(50) NOT NULL,
    student_no VARCHAR(50) NOT NULL,
    class_name VARCHAR(100) NOT NULL,
    is_leader TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 附件
CREATE TABLE IF NOT EXISTS work_attachment (
    id BIGINT NOT NULL,
    work_id BIGINT DEFAULT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    file_url VARCHAR(500) NOT NULL,
    category VARCHAR(20) DEFAULT 'attachment',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 审核
CREATE TABLE IF NOT EXISTS work_audit (
    id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    auditor_id BIGINT NOT NULL,
    result TINYINT NOT NULL,
    reason VARCHAR(500) DEFAULT NULL,
    audit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 发布
CREATE TABLE IF NOT EXISTS work_publish (
    id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    publish_status TINYINT NOT NULL DEFAULT 0,
    featured TINYINT NOT NULL DEFAULT 0,
    publish_time DATETIME DEFAULT NULL,
    offline_time DATETIME DEFAULT NULL,
    publisher_id BIGINT DEFAULT NULL,
    preview_url VARCHAR(500) DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_work_id (work_id)
);

-- 评分
CREATE TABLE IF NOT EXISTS work_score (
    id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    innovation DECIMAL(5,2) NOT NULL DEFAULT 0,
    difficulty DECIMAL(5,2) NOT NULL DEFAULT 0,
    completion DECIMAL(5,2) NOT NULL DEFAULT 0,
    practicality DECIMAL(5,2) NOT NULL DEFAULT 0,
    total DECIMAL(5,2) NOT NULL DEFAULT 0,
    comment TEXT DEFAULT NULL,
    batch_id BIGINT DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_work_teacher (work_id, teacher_id)
);

-- 评论
CREATE TABLE IF NOT EXISTS work_comment (
    id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    parent_id BIGINT DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 评分批次
CREATE TABLE IF NOT EXISTS score_batch (
    id BIGINT NOT NULL,
    batch_name VARCHAR(200) NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    class_scopes TEXT DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    rank_published TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 敏感规则
CREATE TABLE IF NOT EXISTS sensitive_rule (
    id BIGINT NOT NULL,
    rule_name VARCHAR(200) NOT NULL,
    system_prompt TEXT NOT NULL,
    enabled_categories TEXT DEFAULT NULL,
    on_reject_action VARCHAR(50) NOT NULL DEFAULT 'reject',
    status TINYINT NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 奖项配置
CREATE TABLE IF NOT EXISTS reward_config (
    id BIGINT NOT NULL,
    batch_id BIGINT NOT NULL,
    reward_level VARCHAR(20) NOT NULL,
    reward_name VARCHAR(100) NOT NULL DEFAULT '',
    prize_name VARCHAR(200) NOT NULL DEFAULT '',
    quota INT NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 排名奖励配置
CREATE TABLE IF NOT EXISTS rank_reward (
    id BIGINT NOT NULL,
    batch_id BIGINT NOT NULL,
    reward_level INT NOT NULL,
    reward_name VARCHAR(100) NOT NULL DEFAULT '',
    prize_name VARCHAR(200) DEFAULT NULL,
    prize_image VARCHAR(500) DEFAULT NULL,
    quota INT NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 奖品发放
CREATE TABLE IF NOT EXISTS reward_issue (
    id BIGINT NOT NULL,
    reward_id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    issue_status TINYINT NOT NULL DEFAULT 0,
    issue_time DATETIME DEFAULT NULL,
    operator_id BIGINT DEFAULT NULL,
    remark VARCHAR(500) DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

-- 端口管理
CREATE TABLE IF NOT EXISTS port_manage (
    id BIGINT NOT NULL,
    port_number INT NOT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    work_id BIGINT DEFAULT NULL,
    allocated_time DATETIME DEFAULT NULL,
    preview_url VARCHAR(500) DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_port_number (port_number)
);

-- 标签
CREATE TABLE IF NOT EXISTS tag (
    id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    color VARCHAR(20) DEFAULT '#409EFF',
    type VARCHAR(30) DEFAULT 'tech',
    sort INT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_name (name)
);

-- 作品-标签关联
CREATE TABLE IF NOT EXISTS work_tag (
    id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_work_tag (work_id, tag_id)
);

-- 点赞
CREATE TABLE IF NOT EXISTS work_like (
    id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_work_user (work_id, user_id)
);
